on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Repo"
        uses: actions/checkout@v3
      - name: "Build Project"
        run: "echo 'Building code..!'"
  verify: 
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'Verifying compliance'":
