name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: 
        go-version: '>=1.17.0'
    - run: go version

    - name: build
      working-directory: ./go-app
      run: go build -o go-binary main.go

    - name: Test
      working-directory: ./go-app
      run: go test -v ./...

    - name: Upload binary to s3
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        aws s3 cp ./go-app/go-binary s3://${{ secrets.TARGET_BUCKET }}/
   
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download executable from AWS S3
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: | 
        aws s3 cp s3://${{ secrets.TARGET_BUCKET }}/go-binary .
        ls -ltr
        chmod +x ./go-binary
    - name: Set up SSH key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.ACCESS_SECRET }}" > ~/.ssh/private_key.pem
        chmod 600 ~/.ssh/private_key.pem
    - name: Copy Binary to bastion
      run: |
        ls -ltr ~/.ssh/
        scp --o StrictHostKeyChecking=no -i ~/.ssh/private_key.pem ./go-binary ubuntu@18.210.94.217:/tmp/go-binary

    - name: Move binary to App server
      run: |
        ssh -i ~/.ssh/private_key.pem ubuntu@18.210.94.217 \
          "scp /tmp/go-binary anuroop@10.0.0.159:/home/anuroop/"
        
    - name: Verify on App server
      run: |
        ssh -i ~/.ssh/private_key.pem ubuntu@18.210.94.217 \
          "ssh anuroop@10.0.0.159 'hostname && whoami'"
