name: Go


on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latets
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with: 
        go-version: '1.21.5'

    - name: build
      run: go build -v ./...

    - name: Test
        run: go test -v ./...
