name: Go

on:
  push:
    paths:
      - 'go-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: 
        go-version: '>=1.17.0'
    - run: go version

    - name: build
      working-directory: ./go-app
      run: go build -o go-binary main.go

    - name: Test
      working-directory: ./go-app
      run: go test -v ./...

    - name: Upload binary to s3
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        aws s3 cp ./go-app/go-binary s3://${{ secrets.TARGET_BUCKET }}/ 

