name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with: 
        go-version: '>=1.17.0'
    - run: go version

    - name: build
      working-directory: ./go-app
      run: go build -o go-binary main.go

    - name: Test
      working-directory: ./go-app
      run: go test -v ./...

    - name: Upload binary to s3
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
        AWS_DEFAULT_REGION: "us-east-1"
      run: |
        aws s3 cp ./go-app/go-binary s3://${{ secrets.TARGET_BUCKET }}/
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Download S3
        uses: joutvhu/download-s3@v1.0.0
        with:
          aws_access_key_id: ${{ secrets.ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.SECRET_KEY }}
          aws_region: "eu-central-1"
          aws_bucket: ${{ secrets.TARGET_BUCKET }}
          target: .
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: 18.210.94.217
          user: ubuntu
          key: ${{ secrets.ACCESS_SECRET }}
          scp: ./simplemath => /home/ubuntu/app/simplemath
          last_ssh: chmod +x /home/ec2-user/app/simplemath/simplemath
